### ISSUE TITLE
on Arch

### ISSUE THREAD

**Issue by boussou** [ruudud/devdns#15]
I use it on Arch Linux, the proper parameter is :

	-v /run/docker.sock:/var/run/docker.sock

2 remarks regarding --dns option: 
- on Arch it is in   /etc/conf.d/docker
- you should add in the README that The --dns IP addresses are managed by the embedded docker  DNS server a**nd will not be updated in the container's /etc/resolv.conf file** (from the docker doc). I spent a fair amount of time trying to figuring out why it was not updating that file ;-) until I read the doc.

The --dns IP addresses are managed by the embedded DNS server and will not be updated in the container's /etc/resolv.conf file.
The IP addresses passed via the --dns option is used by the embedded DNS server to forward the DNS query if embedded DNS server is unable to resolve a name resolution request from the containers.

**Comment by ruudud** [comment]
Thanks! PR welcomed :-)

Unsure how to find a good way of covering different OS/distro differences in a maintainable way.

**Comment by boussou** [comment]
I really don't see how I can PR.
unless  I just update the readme file?

**Comment by ruudud** [comment]
Yes, please :-) 
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by boussou** [comment]
No time to fork / update. 
Here is the update.


[README.md-2020-01-25-140157.tar.gz](https://github.com/ruudud/devdns/files/4112083/README.md-2020-01-25-140157.tar.gz)
