### ISSUE TITLE
wont work with compose

### ISSUE THREAD

**Issue by ghost** [ruudud/devdns#18]
I have a bunch of containers that I start using docker-compose but it wont register the names and when I kill the stack I see in the logs it removes the names but it never registers them, only if I launch a container on its own

**Comment by ghost** [comment]
I've tried setting the `-e network=` option but that won't work if I set any options `-e` the container starts and stop right way I've even copied the example from the readme and they don't work either if I set any option it dies.

**Comment by ruudud** [comment]
Hey, I'll look into this. What's the version of Docker and Docker Compose you're running with?

**Comment by JeffFaer** [comment]
I'm also running into issues trying to run this with docker-compose:

```
$ docker --version
Docker version 19.03.8, build afacb8b7f0
$ docker-compose --version
docker-compose version 1.25.0, build unknown
$ cat docker-compose.yml 
version: "3.7"

services:
    dns:
        image: ruudud/devdns
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            - DEBUG=1
$ docker-compose up
Starting tmposj513wuq6_dns_1 ... done
Attaching to tmposj513wuq6_dns_1
dns_1  | + domain=test
dns_1  | + fallbackdns=8.8.8.8
dns_1  | + hostmachineip=172.17.0.1
dns_1  | + network=bridge
dns_1  | + naming=default
dns_1  | + read -r -a extrahosts
dns_1  | + dnsmasq_pid=
dns_1  | + dnsmasq_path=/etc/dnsmasq.d/
dns_1  | + RESET='\e[0;0m'
dns_1  | + RED='\e[0;31;49m'
dns_1  | + GREEN='\e[0;32;49m'
dns_1  | + YELLOW='\e[0;33;49m'
dns_1  | + trap shutdown SIGINT SIGTERM
dns_1  | + set -Eeo pipefail
dns_1  | + print_startup_msg
dns_1  | + echo -e '\e[0;33;49m'
dns_1  | + cat
dns_1  | 
dns_1  |  (                      (          )   (
dns_1  |  )\ )                   )\ )    ( /(   )\ )
dns_1  | (()/(    (     (   (   (()/(    )\()) (()/(
dns_1  |  /(_))   )\    )\  )\   /(_))  ((_)\   /(_))
dns_1  | (_))_   ((_)  ((_)((_) (_))_    _((_) (_))
dns_1  | + echo -en '\e[0;0m'
dns_1  | + cat
dns_1  |  |   \  | __| \ \ / /   |   \  | \| | / __|
dns_1  |  | |) | | _|   \ V /    | |) | | .` | \__ \
dns_1  |  |___/  |___|   \_/     |___/  |_|\_| |___/
dns_1  | + echo ''
dns_1  | 
dns_1  | + set_fallback_dns
dns_1  | + sed -i 's/{{FALLBACK_DNS}}/8.8.8.8/' /etc/dnsmasq.conf
dns_1  | Fallback DNS set to 8.8.8.8
dns_1  | + echo 'Fallback DNS set to 8.8.8.8'
dns_1  | + add_wildcard_record
dns_1  | + echo address=/.test/172.17.0.1
dns_1  | + echo -e '\e[0;32;49m+ Added *.test → 172.17.0.1\e[0;0m'
dns_1  | + Added *.test → 172.17.0.1
dns_1  | + add_running_containers
dns_1  | + local ids
dns_1  | ++ docker ps -q
dns_1  | + ids=416787e01a7f
dns_1  | + for id in $ids
dns_1  | + set_container_record 416787e01a7f
dns_1  | + local cid=416787e01a7f ip name safename record cnetwork
dns_1  | + cnetwork=bridge
dns_1  | + [[ bridge == \a\u\t\o ]]
dns_1  | ++ docker inspect -f '{{with index .NetworkSettings.Networks "bridge"}}{{.IPAddress}}{{end}}' 416787e01a7f
dns_1  | ++ head -n1
dns_1  | + ip=
dns_1  | ++ get_name 416787e01a7f
dns_1  | ++ local cid=416787e01a7f
dns_1  | ++ docker inspect -f '{{ .Name }}' 416787e01a7f
dns_1  | ++ sed 's,^/,,'
dns_1  | + name=tmposj513wuq6_dns_1
dns_1  | ++ get_safe_name tmposj513wuq6_dns_1
dns_1  | ++ local name=tmposj513wuq6_dns_1
dns_1  | ++ case "$naming" in
dns_1  | ++ [[ ! tmposj513wuq6_dns_1 =~ ^[a-zA-Z0-9.-]+$ ]]
dns_1  | ++ name=tmposj513wuq6
dns_1  | ++ echo tmposj513wuq6
dns_1  | + safename=tmposj513wuq6
dns_1  | + record=tmposj513wuq6.test
dns_1  | + set_record tmposj513wuq6.test ''
dns_1  | + local record=tmposj513wuq6.test ip= fpath infomsg
dns_1  | + fpath=/etc/dnsmasq.d/tmposj513wuq6.test.conf
dns_1  | + [[ -z '' ]]
dns_1  | + return 1
tmposj513wuq6_dns_1 exited with code 1
```

Running it manually with `docker run` seems to work:
```
$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:ro ruudud/devdns
 
 (                      (          )   (
 )\ )                   )\ )    ( /(   )\ )
(()/(    (     (   (   (()/(    )\()) (()/(
 /(_))   )\    )\  )\   /(_))  ((_)\   /(_))
(_))_   ((_)  ((_)((_) (_))_    _((_) (_))
 |   \  | __| \ \ / /   |   \  | \| | / __|
 | |) | | _|   \ V /    | |) | | .` | \__ \
 |___/  |___|   \_/     |___/  |_|\_| |___/

Fallback DNS set to 8.8.8.8
+ Added *.test → 172.17.0.1
+ Added determined.test → 172.17.0.2
```

**Comment by danielporto** [comment]
I've got the same problem.
Even if i start devdns directly, my containers started with docker-compose all map to a single name. they dont show up in the devdns output upon starting but does show when I kill them (control +C).

**Comment by ruudud** [comment]
I think you might be reporting different problems depending on your setups.

I've identified a bug when it registers running containers during startup. I've pushed a small fix. That probably solves @JeffreyFalgout problem. Could you test? 
I'll work on providing more helpful warning messages when it catches these cases.

@danielporto the reason they all map to the same names is probably the up-to-the-first-underscore logic. Try setting `-e NAMING=full` config as per [the README](https://github.com/ruudud/devdns/#configuration).

@jasonkristian are you running devdns "outside" of the docker-compose or inside? The push I fixed should help in any case.
If running devdns outside, and you're not too dependent on the networking things compose sets up, you can add `network_mode: bridge` to each service.

**Comment by JeffFaer** [comment]
@ruudud looks like it works now, thanks!

It's probably worth noting somewhere that `NAMING=full` is more or less required for docker-compose set ups, since all containers get named something like `${directory}_${service}_${N}`.

**Comment by ruudud** [comment]
@JeffreyFalgout Yeah, makes sense. I am however interested in how you use devdns in combination with docker-compose.

1. What network mode do you use? Whatever default compose sets up, or `bridge`?
2. Where do you run devdns? Inside the same compose definition as your services? Outside as a "plain" container, and then services within compose?
3. If you run it within compose alongside services, what benefit do you get from devdns? I mean, since compose by default [resolves](https://docs.docker.com/compose/networking/) the other services by service name?

**Comment by JeffFaer** [comment]
1. Whatever default compose sets up (which I believe is bridge)
2. I was running it in the same compose definition as my services
3. I've been running some services in docker that I use on my local network. I've been experimenting with ways to automatically update a local DNS to point to the correct machine running the docker services (so that other computers on my local network can access the service, like the running https://plex.tv service). It seems like devdns would be a simpler version of https://traefik.io for this purpose

**Comment by ruudud** [comment]
Cool, thanks for answering.

Closing this issue as I believe things are in a better shape now. Feel free to open another issue if I'm mistaken.
