### ISSUE TITLE
Double network interface on container fails

### ISSUE THREAD

**Issue by Want100Cookies** [ruudud/devdns#7]
When a container has two network interfaces the devdns container generates an error in the corresponding <hostname>.conf file under /etc/dnsmasq.d

For example I have traefik running with an local and an external network.

Devdns generates the following:
```
bash-4.3# cat traefik.docker.conf
address=/.traefik.docker/172.17.0.2172.24.0.2
bash-4.3#
```

And dnsmasq does not accept this.
```
bash-4.3# dnsmasq --test

dnsmasq: bad address at line 1 of /etc/dnsmasq.d/traefik.docker.conf
```

How should I fix this?

**Comment by ruudud** [comment]
Hi! Could you describe how you run your container so I can consistently reproduce?

**Comment by Want100Cookies** [comment]
First run traefik in de bridge network (default network): (any container would do tbh)
`docker run -d -p 8080:8080 -p 80:80 -p 443:443 -v $PWD/traefik.toml:/etc/traefik/traefik.toml traefik`

Create a new network (or use an existing one):
`docker network create internal`

And then join the existing container to the new network:
`docker network connect internal traefik`

See [docker.com](https://success.docker.com/article/multiple-docker-networks) for more info

**Comment by Want100Cookies** [comment]
After researching a bit I think the error lies here:
**https://github.com/ruudud/devdns/blob/master/run.sh#L77**
The golang temple action 'range' enumerates the Networks section and then displays all IP's.

After researching a bit about golang templating I have  come up with the following template to get the ip in a specific network:
`docker inspect -f '{{.NetworkSettings.Networks.<network name>.IPAddress}}' "<container id>"`

Perhaps there is a nice way to use an environment variable in the container to specify the correct network for devdns lik `DEVDNS_NETWORK=bridge` and then using the docker inspect to get this value.

I have not yet found a way to only get the first IP (for use in a situation where no env var is provided, so a default value).

**Comment by ruudud** [comment]
OK, I have a setup reproducing the issue now.

I agree that having an env variable specifying the network makes sense (with `bridge` as the default variable).

Another alternative would be for the devdns container to self-inspect what network it is part of, and then use this when getting the IP addresses of the other containers.

Eg. from within the devdns container;
```sh
cid="$(basename $(cat /proc/1/cpuset))"
network="$(docker inspect -f '{{range $key, $val := .NetworkSettings.Networks }}{{ $key }}{{ end }}' $cid)"
```

Of course, this breaks the moment the devdns container also has more than one network attached.. :smiley:
